name: Build jamovi Module

on:
  push:
    branches: [ main ] # This runs the action every time you push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository's code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up Node.js, which is needed to run the compiler
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a current LTS version of Node.js

    # 3. Download the jamovi compiler
    - name: Download jamovi-compiler
      run: npm install jamovi-compiler

    # 4. Run the compiler to build the .jmo file
    - name: Build module
      run: ./node_modules/.bin/jmc --build .

    # 5. Upload the .jmo file as a downloadable artifact
    - name: Upload .jmo artifact
      uses: actions/upload-artifact@v4
      with:
        name: jamovi-module
        path: '*.jmo'
