name: Build jamovi Module

on:
  push:
    branches: [ main ] # This runs the action every time you push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out your repository's code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Set up R environment
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2' # Use a version of R compatible with jamovi

    # 3. Install jmvtools and its dependencies
    - name: Install jmvtools
      run: |
        install.packages('jmvtools', repos=c('https://repo.jamovi.org', 'https://cran.r-project.org'))
      shell: Rscript {0}

    # 4. Build the module using jmvtools
    - name: Build module
      run: jmvtools::install()
      shell: Rscript {0}

    # 5. Upload the .jmo file as a downloadable artifact
    - name: Upload .jmo artifact
      uses: actions/upload-artifact@v4
      with:
        name: jamovi-module
        path: '*.jmo'
